import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        padding: 30,
        paddingTop: 60,
    },
    title: {
        fontSize: 40,
        color: '#000',
        marginTop: 20,
        marginBottom: 20,
    },
    form: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
    },
    switchButton: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    input: {
        margin: 4,
        borderWidth: 2,
        padding: 15,
        borderRadius: 5,
        width: '100%',
    },
    inputError: {
        margin: 4,
        borderWidth: 2,
        borderColor: 'red',
        padding: 15,
        borderRadius: 5,
        width: '100%',
    },
    button: {
        backgroundColor: '#000',
        marginTop: 15,
        padding: 17,
        borderRadius: 5,
        width: '100%'
    },
    buttonText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
    buttonUpload: {
        backgroundColor: '#E8E8E8',
        marginTop: 15,
        padding: 17,
        borderRadius: 5,
        width: '100%',
    },
    radioGroup: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        marginBottom: 5,
        marginTop: 10,
        padding: 10,
    },
    radioButton: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    forgotPassword: {
        width: '100%',
        padding: 20,
        alignItems: 'flex-start',
    },
    forgotPasswordText: {
        color: '#C6C4C4',
        fontSize: 14,
        fontWeight: 'bold',
        textDecorationLine: 'underline',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
    },
    history: {
        width: '100%',
        padding: 10,
        alignItems: 'center',
    },
    historyText: {
        color: '#C6C4C4',
        fontSize: 16,
        fontWeight: 'bold',
        textDecorationLine: 'underline',
    },
    containerHome: {
        flex: 1,
        justifyContent: 'center',
    },
    buttonRounded: {
        backgroundColor: '#000',
        padding: 17,
        borderRadius: 50,
        width: '100%',
        alignItems: 'center',
    },
    containerProfile: {
        flex: 1,
        paddingTop: 40,
        alignItems: 'center',
    },
    image: {
        width: 125,
        height: 125,
        borderRadius: 60,
        marginBottom: 10,
    },
    name: {
        fontSize: 20,
        color: '#000',
        fontWeight: 'bold',
    },
    fields: {
        width: '100%',
        marginTop: 40,
    },
    field: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 10,
    },
    fieldsText: {
        fontSize: 17,
    },
    subTitle: {
        fontSize: 20,
        color: '#E8E8E8',
        fontWeight: 'bold',
        marginTop: 20,
        marginLeft: 10,
    },
    map: {
        flex: 1,
        width: '100%',
        height: '100%',
    },
    swipe: {
        flex: 1,
        width: '100%',
        height: 300,
        backgroundColor: '#fff',
        borderTopLeftRadius: 35,
        borderTopRightRadius: 35,
        position: 'absolute',
        bottom: 0,
        paddingLeft: 30,
        paddingRight: 30,
        paddingTop: 10,
        alignItems: 'center',
    },
    swipeButton: {
        backgroundColor: '#E8E8E8',
        height: 6,
        width: 48,
        borderRadius: 5,
        alignItems: 'center',
        marginBottom: 15,
    },
    swipeTitle: {
        fontSize: 20,
        color: '#000',
        fontWeight: 'bold',
    },
    containerTime: {
        backgroundColor: '#000',
        padding: 8,
        borderRadius: 35,
        width: 70,
        height: 70,
        alignItems: 'center',
    },
    time: {
        fontSize: 25,
        color: '#fff',
        fontWeight: 'bold',
    },
    timeText: {
        fontSize: 12,
        color: '#fff',
        fontWeight: 'bold',
    },
    line: {
        width: '130%',
        height: 2,
        backgroundColor: '#E8E8E8',
        marginTop: 10,
        marginBottom: 10,
    },
    containerModal: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        paddingTop: 10,
    },
    infoDriver: {
        alignItems: 'flex-start',
    },
    plate: {
        fontSize: 32,
        fontWeight: 'bold',
    },
    imageDriver: {
        width: 95,
        height: 95,
        borderRadius: 60,
    },
    messageContainer: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        alignContent: 'center',
        alignSelf: 'center',
        justifyContent: 'space-between',
        marginTop: 15,
        marginRight: 10,
    },
    messageInput: {
        backgroundColor: '#E8E8E8',
        padding: 10,
        paddingLeft: 20,
        borderRadius: 25,
        width: '90%',
    },
    stars: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 10,
    },
    optionTouchable1:{
        width: '120%',
        backgroundColor: '#E8E8E8',
        alignSelf: 'center',
        alignContent: 'center',
        alignItems: 'center',
    },
    optionTouchable2:{
        width: '120%',
        backgroundColor: '#fff',
        alignSelf: 'center',
        alignContent: 'center',
        alignItems: 'center',
    },
    optionContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '85%',
        margin: 20,
    },
    optionInfo: {
        alignItems: 'flex-start',
    },
    optionPrice: {
        fontSize: 24,
        fontWeight: 'bold',
    },
    optionTitle: {
        fontSize: 16,
        color: '#000',
        fontWeight: 'bold',
    },
    optionText: {
        fontSize: 14,
    },

})